#!/usr/bin/env python

from proppy import MetaProppy
from proppy.props import WriteOnceProperty, Property


class TestClass(metaclass=MetaProppy):
    x__prop = Property('Hello')
    c__prop = WriteOnceProperty(30)


def main():
    tst1 = TestClass()
    tst2 = TestClass()

    tst1.x = "OK!"
    tst1.c = 100
    tst1.c = 50

    tst2.c = 35

    print(tst1.x)
    print(tst1.c)

    print()

    print(tst2.x)
    print(tst2.c)

if __name__ == '__main__':
    main()
